import { escapeHtml, renderProtectedShell, route, showDialog } from "./shared.js";

type Customer = { id: number; firstName: string; lastName: string; email: string; phone: string; company: string; jobTitle: string; status: string; address: string; notes: string; createdAt: string };
type Note = { id: number; content: string; createdAt: string };
type Attachment = { id: number; fileName: string; contentType: string; size: number };
type Interaction = { id: number; type: string; content: string; createdAt: string };
type Communication = { id: number; ticketId: number | null; channel: string; message: string; receivedAt: string };
const statuses = [{ value: "active", label: "Active" }, { value: "prospect", label: "Prospect" }, { value: "inactive", label: "Inactive" }];

export async function renderCustomerDetails(id: number) {
  renderProtectedShell(`<div id="page-content"><div class="customer-loading"><span class="loading-orb"></span><p>Loading customer details...</p></div></div>`, window.location.pathname);
  const content = document.querySelector<HTMLDivElement>("#page-content")!;
  const [customerResponse, notesResponse, attachmentsResponse, interactionsResponse] = await Promise.all([fetch(`/api/customers/${id}`, { credentials: "same-origin" }), fetch(`/api/customers/${id}/notes`, { credentials: "same-origin" }), fetch(`/api/customers/${id}/attachments`, { credentials: "same-origin" }), fetch(`/api/customers/${id}/interactions`, { credentials: "same-origin" })]);
  if (!customerResponse.ok) { content.innerHTML = `<div class="customer-error" role="alert"><strong>Customer not found.</strong><span>Return to the customer directory to try again.</span><button id="back-customers" type="button">Back to customers</button></div>`; document.querySelector("#back-customers")!.addEventListener("click", () => { history.pushState({}, "", "/customers"); void route(); }); return; }
  const customer = await customerResponse.json() as Customer;
  const notes = notesResponse.ok ? await notesResponse.json() as Note[] : [];
  const attachments = attachmentsResponse.ok ? await attachmentsResponse.json() as Attachment[] : [];
  const interactions = interactionsResponse.ok ? await interactionsResponse.json() as Interaction[] : [];
  const communicationsResponse = await fetch(`/api/customers/${id}/communications`, { credentials: "same-origin" });
  const communications = communicationsResponse.ok ? await communicationsResponse.json() as Communication[] : [];
  const value = (text: unknown) => escapeHtml(String(text || "Not provided"));
  const communicationRows = communications.length ? communications.map((item) => `<article><strong>${value(item.channel)}</strong><p>${value(item.message)}</p><small>${value(new Date(item.receivedAt).toLocaleString())}${item.ticketId !== null ? ` · <a href="/tickets/${item.ticketId}">Ticket #${item.ticketId}</a>` : ""}</small></article>`).join("") : "<p>No communications yet.</p>";
  const noteRows = notes.length ? notes.map((note) => `<article><p>${value(note.content)}</p><small>${value(new Date(note.createdAt).toLocaleString())}</small><button type="button" data-note-edit="${note.id}">Edit</button><button type="button" data-note-delete="${note.id}">Delete</button></article>`).join("") : "<p>No notes yet.</p>";
  const attachmentRows = attachments.length ? attachments.map((attachment) => `<article><a href="/api/customers/${id}/attachments/${attachment.id}">${value(attachment.fileName)}</a><small>${value(attachment.contentType)} - ${attachment.size} bytes</small><button type="button" data-attachment-delete="${attachment.id}">Delete</button></article>`).join("") : "<p>No attachments yet.</p>";
  const interactionRows = interactions.length ? interactions.map((interaction) => `<article><strong>${value(interaction.type)}</strong><p>${value(interaction.content)}</p><small>${value(new Date(interaction.createdAt).toLocaleString())}</small></article>`).join("") : "<p>No interactions yet.</p>";
  content.innerHTML = `<button type="button" class="back-link" id="back-customers">Back to customers</button><div class="detail-heading"><div><span class="eyebrow">Customer profile</span><h1>${value(customer.firstName)} ${value(customer.lastName)}</h1><p class="form-intro">Customer relationship overview</p></div><span class="status-badge ${value(customer.status)}">${value(customer.status)}</span></div><div class="customer-actions"><button type="button" id="edit-customer">Edit customer</button><button type="button" id="change-status">Change status</button></div><div class="customer-details">${[["First name", customer.firstName], ["Last name", customer.lastName], ["Email", customer.email], ["Phone", customer.phone], ["Company", customer.company], ["Job title", customer.jobTitle], ["Address", customer.address], ["Created", new Date(customer.createdAt).toLocaleDateString()], ["Profile notes", customer.notes]].map(([label, text]) => `<div><span>${label}</span><strong>${value(text)}</strong></div>`).join("")}</div><div class="record-sections"><section class="related-section"><span class="eyebrow">Notes</span><form id="note-form"><textarea name="content" maxlength="500" required placeholder="Add a note"></textarea><button type="submit">Add note</button></form><div id="notes-list">${noteRows}</div></section><section class="related-section"><span class="eyebrow">Attachments</span><form id="attachment-form" enctype="multipart/form-data"><input name="file" type="file" required /><button type="submit">Upload attachment</button></form><div>${attachmentRows}</div></section><section class="related-section"><span class="eyebrow">Interactions</span><form id="interaction-form"><select name="type"><option value="call">Call</option><option value="email">Email</option><option value="message">Message</option><option value="meeting">Meeting</option><option value="note">Note</option></select><textarea name="content" maxlength="500" required placeholder="Record an interaction"></textarea><button type="submit">Add interaction</button></form><div>${interactionRows}</div></section><section class="related-section"><span class="eyebrow">Communications</span><div>${communicationRows}</div></section></div>`;
  document.querySelector("#back-customers")!.addEventListener("click", () => { history.pushState({}, "", "/customers"); void route(); });
  document.querySelector("#edit-customer")!.addEventListener("click", () => void editCustomer(customer));
  document.querySelector("#change-status")!.addEventListener("click", () => void changeStatus(customer));
  document.querySelector<HTMLFormElement>("#note-form")!.addEventListener("submit", (event) => void submitRelated(event, `/api/customers/${id}/notes`));
  document.querySelector<HTMLFormElement>("#interaction-form")!.addEventListener("submit", (event) => void submitRelated(event, `/api/customers/${id}/interactions`));
  document.querySelector<HTMLFormElement>("#attachment-form")!.addEventListener("submit", async (event) => { event.preventDefault(); const response = await fetch(`/api/customers/${id}/attachments`, { method: "POST", body: new FormData(event.currentTarget as HTMLFormElement), credentials: "same-origin" }); if (response.ok) await renderCustomerDetails(id); });
  document.querySelectorAll<HTMLButtonElement>("[data-note-delete]").forEach((button) => button.addEventListener("click", async () => { if (await showDialog({ title: "Delete note", message: "This note will be permanently removed.", confirmLabel: "Delete" })) { await fetch(`/api/customers/${id}/notes/${button.dataset.noteDelete}`, { method: "DELETE", credentials: "same-origin" }); await renderCustomerDetails(id); } }));
  document.querySelectorAll<HTMLButtonElement>("[data-note-edit]").forEach((button) => button.addEventListener("click", async () => { const note = notes.find((item) => item.id === Number(button.dataset.noteEdit)); const content = await showDialog({ title: "Edit note", message: "Update this customer note.", input: note?.content ?? "", confirmLabel: "Save note" }); if (content !== null) { await fetch(`/api/customers/${id}/notes/${button.dataset.noteEdit}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }), credentials: "same-origin" }); await renderCustomerDetails(id); } }));
  document.querySelectorAll<HTMLButtonElement>("[data-attachment-delete]").forEach((button) => button.addEventListener("click", async () => { if (await showDialog({ title: "Delete attachment", message: "This file will be removed from the customer record.", confirmLabel: "Delete" })) { await fetch(`/api/customers/${id}/attachments/${button.dataset.attachmentDelete}`, { method: "DELETE", credentials: "same-origin" }); await renderCustomerDetails(id); } }));
}

async function submitRelated(event: SubmitEvent, url: string) { event.preventDefault(); const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget as HTMLFormElement).entries())), credentials: "same-origin" }); if (response.ok) await renderCustomerDetails(Number(window.location.pathname.split("/")[2])); }
async function editCustomer(customer: Customer) { const firstName = await showDialog({ title: "Edit customer", message: "Update the customer's first name.", input: customer.firstName, confirmLabel: "Save changes" }); if (firstName === null) return; await fetch(`/api/customers/${customer.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...customer, firstName }), credentials: "same-origin" }); await renderCustomerDetails(customer.id); }
async function changeStatus(customer: Customer) { const status = await showDialog({ title: "Change customer status", message: "Choose the current status for this customer.", select: statuses.map((option) => ({ ...option, selected: option.value === customer.status })), confirmLabel: "Update status" }); if (status === null) return; await fetch(`/api/customers/${customer.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...customer, status }), credentials: "same-origin" }); await renderCustomerDetails(customer.id); }
