import { escapeHtml, renderProtectedShell, route } from "./shared.js";

type Ticket = { id:number; ticketNumber:string; customerId:number; customerName:string; customerEmail:string; subject:string; description:string; category:string; priority:string; assignedAgent:string; status:string; dueDate:string|null; isEscalated:boolean; slaRuleId:number|null; responseTargetMinutes:number|null; responseDueAt:string|null; responseRespondedAt:string|null; resolutionTargetMinutes:number|null; resolutionDueAt:string|null };
type History = { id:number; action:string; oldValue:string|null; newValue:string|null; changedBy:string; createdAt:string };
type Communication = { id:number; channel:string; message:string; receivedAt:string };
type InternalComment = { id:number; body:string; createdBy:string; createdAt:string };
const statuses = ["new", "open", "in_progress", "pending", "resolved", "closed"], priorities = ["low", "medium", "high", "urgent"];
const value = (input:unknown) => escapeHtml(String(input ?? "Not provided"));
const selectOptions = (items:string[], selected:string) => items.map(item => `<option value="${item}"${item === selected ? " selected" : ""}>${value(item.replace("_", " "))}</option>`).join("");

export async function renderTicketDetails(id:number) {
  renderProtectedShell(`<div id="page-content"><div class="customer-loading"><span class="loading-orb"></span><p>Loading ticket...</p></div></div>`, window.location.pathname);
  const content = document.querySelector<HTMLDivElement>("#page-content")!;
  const [ticketResponse, historyResponse, communicationsResponse, commentsResponse] = await Promise.all([
    fetch(`/api/tickets/${id}`, { credentials:"same-origin" }), fetch(`/api/tickets/${id}/history`, { credentials:"same-origin" }), fetch(`/api/tickets/${id}/communications`, { credentials:"same-origin" }), fetch(`/api/tickets/${id}/comments`, { credentials:"same-origin" })
  ]);
  if (!ticketResponse.ok) { content.innerHTML = `<div class="customer-error"><strong>Ticket not found.</strong><button id="back-tickets" type="button">Back to tickets</button></div>`; document.querySelector("#back-tickets")!.addEventListener("click", () => { history.pushState({}, "", "/tickets"); void route(); }); return; }
  const ticket = await ticketResponse.json() as Ticket;
  const historyRows = historyResponse.ok ? await historyResponse.json() as History[] : [];
  const communications = communicationsResponse.ok ? await communicationsResponse.json() as Communication[] : [];
  const comments = commentsResponse.ok ? await commentsResponse.json() as InternalComment[] : [];
  const communicationRows = communications.length ? communications.map(item => `<article><strong>${value(item.channel)}</strong><p>${value(item.message)}</p><small>${value(new Date(item.receivedAt).toLocaleString())}</small></article>`).join("") : "<p>No communications yet.</p>";
  const commentRows = comments.length ? comments.map(comment => `<article><p>${value(comment.body)}</p><small>${value(comment.createdBy)} · ${value(new Date(comment.createdAt).toLocaleString())}</small></article>`).join("") : "<p>No internal comments yet.</p>";
  content.innerHTML = `<button type="button" class="back-link" id="back-tickets">Back to tickets</button><div class="detail-heading"><div><span class="eyebrow">${value(ticket.ticketNumber)}</span><h1>${value(ticket.subject)}</h1><p class="form-intro">${value(ticket.customerName)} — ${value(ticket.customerEmail)}</p></div><span class="ticket-badge ${value(ticket.priority)}">${value(ticket.priority)}</span></div><div id="ticket-feedback" role="status"></div><form class="ticket-form" id="ticket-edit-form"><div class="customer-fields"><label>Customer<input value="${value(ticket.customerName)}" disabled /></label><label>Subject *<input name="subject" maxlength="200" value="${value(ticket.subject)}" required /></label><label>Category *<input name="category" maxlength="100" value="${value(ticket.category)}" required /></label><label>Priority *<select name="priority">${selectOptions(priorities, ticket.priority)}</select></label><label>Assigned agent *<input name="assignedAgent" maxlength="200" value="${value(ticket.assignedAgent)}" required /></label><label>Status *<select name="status">${selectOptions(statuses, ticket.status)}</select></label><label>Due date<input name="dueDate" type="date" value="${value(ticket.dueDate ?? "")}" /></label><label class="wide-field">Description *<textarea name="description" maxlength="2000" required>${value(ticket.description)}</textarea></label></div><p role="alert" id="ticket-error"></p><div class="form-actions"><button type="submit">Save changes</button><button type="button" class="cancel-button" id="escalate-ticket" ${ticket.isEscalated ? "disabled" : ""}>${ticket.isEscalated ? "Escalated" : "Escalate"}</button></div></form><section class="ticket-history"><span class="eyebrow">History</span>${historyRows.length ? historyRows.map(entry => `<article><strong>${value(entry.action.replaceAll("_", " "))}</strong><span>${entry.oldValue !== null || entry.newValue !== null ? `${value(entry.oldValue)} → ${value(entry.newValue)}` : "Ticket updated"}</span><small>${value(entry.changedBy)} · ${value(new Date(entry.createdAt).toLocaleString())}</small></article>`).join("") : "<p>No history yet.</p>"}</section><section class="ticket-history"><span class="eyebrow">Communications</span>${communicationRows}</section><section class="ticket-history"><span class="eyebrow">Internal comments</span><p>Internal only — not visible to customers.</p><form id="comment-form"><label for="quick-reply">Quick reply</label><select id="quick-reply"><option value="">Choose a template</option><option>I am reviewing this now.</option><option>Please share any additional details.</option><option>This has been escalated to the support team.</option></select><label for="comment-body">Comment *</label><textarea id="comment-body" name="body" maxlength="2000" required placeholder="Add an internal comment"></textarea><p id="comment-error" role="alert"></p><button type="submit">Add internal comment</button></form>${commentRows}</section>`;
  const categoryInput = content.querySelector<HTMLInputElement>('input[name="category"]')!;
  const categoryValues = ["Access", "Account", "Billing", "Communication", "Support", "Technical", "Other"];
  if (!categoryValues.includes(ticket.category)) categoryValues.push(ticket.category);
  const categorySelect = document.createElement("select");
  categorySelect.name = "category";
  categorySelect.required = true;
  categorySelect.innerHTML = categoryValues.map((category) => `<option value="${value(category)}"${category === ticket.category ? " selected" : ""}>${value(category)}</option>`).join("");
  categoryInput.replaceWith(categorySelect);
  const deadline=(date:string|null, stopped:boolean)=>!date ? "Not configured" : stopped ? `Stopped ${value(new Date(date).toLocaleString())}` : `${new Date(date).getTime() < Date.now() ? "Overdue" : "Due"} ${value(new Date(date).toLocaleString())}`;
  const slaSection=document.createElement("section"); slaSection.className="ticket-history sla-state";
  slaSection.innerHTML=`<span class="eyebrow">SLA</span>${ticket.slaRuleId ? `<article><strong>Rule #${ticket.slaRuleId}</strong><span>Response target: ${ticket.responseTargetMinutes} minutes — ${deadline(ticket.responseDueAt,Boolean(ticket.responseRespondedAt))}</span><span>Resolution target: ${ticket.resolutionTargetMinutes} minutes — ${deadline(ticket.resolutionDueAt,["resolved","closed"].includes(ticket.status))}</span>${ticket.responseRespondedAt ? `<small>First response sent ${value(new Date(ticket.responseRespondedAt).toLocaleString())}</small>` : `<button id="mark-responded" type="button">Mark first response sent</button>`}</article>` : "<p>No SLA rule matched this ticket.</p>"}`;
  document.querySelector<HTMLFormElement>("#ticket-edit-form")!.insertAdjacentElement("afterend",slaSection);
  document.querySelector<HTMLButtonElement>("#mark-responded")?.addEventListener("click",async event=>{const button=event.currentTarget as HTMLButtonElement;button.disabled=true;const response=await fetch(`/api/tickets/${id}/responded`,{method:"POST",credentials:"same-origin"});if(response.ok)await renderTicketDetails(id);else button.disabled=false;});
  document.querySelector("#back-tickets")!.addEventListener("click", () => { history.pushState({}, "", "/tickets"); void route(); });
  document.querySelector<HTMLFormElement>("#ticket-edit-form")!.addEventListener("submit", async event => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement, button = form.querySelector<HTMLButtonElement>("button[type=submit]")!, error = form.querySelector<HTMLElement>("#ticket-error")!; button.disabled = true; const response = await fetch(`/api/tickets/${id}`, { method:"PATCH", credentials:"same-origin", headers:{ "Content-Type":"application/json" }, body:JSON.stringify({ ...Object.fromEntries(new FormData(form).entries()), customerId:ticket.customerId }) }); const body = await response.json(); if (!response.ok) { error.textContent = Object.values(body.errors ?? {}).join(" ") || body.error || "Unable to update ticket."; button.disabled = false; return; } await renderTicketDetails(id); });
  document.querySelector<HTMLSelectElement>("#quick-reply")!.addEventListener("change", event => { const reply = (event.currentTarget as HTMLSelectElement).value; if (reply) document.querySelector<HTMLTextAreaElement>("#comment-body")!.value = reply; });
  document.querySelector<HTMLFormElement>("#comment-form")!.addEventListener("submit", async event => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement, button = form.querySelector<HTMLButtonElement>("button")!, error = form.querySelector<HTMLElement>("#comment-error")!; button.disabled = true; error.textContent = ""; const response = await fetch(`/api/tickets/${id}/comments`, { method:"POST", credentials:"same-origin", headers:{ "Content-Type":"application/json" }, body:JSON.stringify(Object.fromEntries(new FormData(form).entries())) }); if (response.ok) { await renderTicketDetails(id); return; } const body = await response.json().catch(() => ({})) as { errors?:Record<string,string>; error?:string }; error.textContent = Object.values(body.errors ?? {}).join(" ") || body.error || "Unable to add internal comment."; button.disabled = false; });
  document.querySelector<HTMLButtonElement>("#escalate-ticket")!.addEventListener("click", async event => { const button = event.currentTarget as HTMLButtonElement; button.disabled = true; const response = await fetch(`/api/tickets/${id}/escalate`, { method:"POST", credentials:"same-origin" }); if (response.ok) await renderTicketDetails(id); else { button.disabled = false; document.querySelector<HTMLElement>("#ticket-error")!.textContent = "Unable to escalate ticket."; } });
}
